gui:
  title: "Adventskalender"
  layout:
  # "---------"
  - " d dd d d"
  - "d d  d d "
  - "d d d d d"
  - "d  dd  dd"
  - " dd d d d"
  # insert items
  filler:
    ==: org.bukkit.inventory.ItemStack
    type: LEAVES
    damage: 1
  icons:
    day:
      unavailable:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PwW6CQBRFX5s0saSf0S3JCA7Kogsjpg7RoaCAw47BQRgGaxQs8F39wLLs8uacs7gagAZv+6pV6uv2nZdKTOCZnOCdc5zPpguk2wue6zM7s/TUwIbOZ7YtsMXnuWFpoI3RVdyaUtxfYdKIrmlv4q4BwNMEXqJUtQJ+Re+i5Fig09FVWU+scR/2SHlEXufkEvV8RSxSj3yztLa9/c/FTRpjxUy3SC5+y+sIbc1AiU0wzerwkchsYPJsUqlK6rAuOZwNGtPSc6Jq9xn+0Hg9UKeQbPC7XR1JOiw7JouaGWvsxUFFYx9RGUgvDntqMMykj3Yr186P6GN8AH8rN78yHAEAAA==
      available:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PwW6CQBRFX5s0saSf0S3JCA7Kogsjpg7RoaCAw47BQRgGaxQs8F39wLLs8uacs7gagAZv+6pV6uv2nZdKTOCZnOCdc5zPpguk2wue6zM7s/TUwIbOZ7YtsMXnuWFpoI3RVdyaUtxfYdKIrmlv4q4BwNMEXqJUtQJ+Re+i5Fig09FVWU+scR/2SHlEXufkEvV8RSxSj3yztLa9/c/FTRpjxUy3SC5+y+sIbc1AiU0wzerwkchsYPJsUqlK6rAuOZwNGtPSc6Jq9xn+0Hg9UKeQbPC7XR1JOiw7JouaGWvsxUFFYx9RGUgvDntqMMykj3Yr186P6GN8AH8rN78yHAEAAA==
      retrieved:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PQW+CMBiGvy1Z4sh+xq4kRSjCYQcznZZI2bQK7U1KndbWGQUD/q79wHHc8c3zPIfXAXDgZXVsjPm8/OwORg3gkVTwOpL+SEaxcmWoSjfAgXSjyI9d5OOo9NSwiivPAaePzupSH9T1GQa1auvmoq4OADwM4GmzNY2CX9UlSBR7VBWJkR0J+81WyGREn0fktOnKdxIS2/P5OFx08T8X19scG+4ne3H6akq7QQt/adR86Um7vnFGOs4+NNW8o1qidDZtU3ZsxWTspXqMaT4NBBN7kROPWo6zGblnE3FMrbCCfQd0SG3G0ju16yHXU8zvRvNDEu8K9NY/gD+IatwxHAEAAA==
      missed:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PvW6DMBhFv1aqRFEfoyuSCQHK0CH9S4yCaRICmM0mpmDsNEogCnmuPmDp1uEOV+fc4ZoAJjxs2l6pz+N31ShhwC3ewaPzxIKKcd9iPODWlAtuBYxxy54y4Qbc83npm2COo4M4do043YPRiUvXH8XJBIAbA+5SpnoBP2IIUZHXaJeHqhywN/Zkg1SM5cHH+3Tgr9jDeuSLmbccgn+u27HMVdQJ62K/6rlO0dJZK7FY26XenklGByqJJhPSUrl1o2uLaPIi47dQFwl1/hLJLxTplUOSVBZJreJ52hbzD1Vk2KUylfT67kQTbJNkdhl5S5owqHL0PD6AX2ZylXgcAQAA
    advent:
      unavailable:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PwW6CQBRFX5s0saSf0S3JCA7Kogsjpg7RoaCAw47BQRgGaxQs8F39wLLs8uacs7gagAZv+6pV6uv2nZdKTOCZnOCdc5zPpguk2wue6zM7s/TUwIbOZ7YtsMXnuWFpoI3RVdyaUtxfYdKIrmlv4q4BwNMEXqJUtQJ+Re+i5Fig09FVWU+scR/2SHlEXufkEvV8RSxSj3yztLa9/c/FTRpjxUy3SC5+y+sIbc1AiU0wzerwkchsYPJsUqlK6rAuOZwNGtPSc6Jq9xn+0Hg9UKeQbPC7XR1JOiw7JouaGWvsxUFFYx9RGUgvDntqMMykj3Yr186P6GN8AH8rN78yHAEAAA==
      available:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PwW6CQBRFX5s0saSf0S3JCA7Kogsjpg7RoaCAw47BQRgGaxQs8F39wLLs8uacs7gagAZv+6pV6uv2nZdKTOCZnOCdc5zPpguk2wue6zM7s/TUwIbOZ7YtsMXnuWFpoI3RVdyaUtxfYdKIrmlv4q4BwNMEXqJUtQJ+Re+i5Fig09FVWU+scR/2SHlEXufkEvV8RSxSj3yztLa9/c/FTRpjxUy3SC5+y+sIbc1AiU0wzerwkchsYPJsUqlK6rAuOZwNGtPSc6Jq9xn+0Hg9UKeQbPC7XR1JOiw7JouaGWvsxUFFYx9RGUgvDntqMMykj3Yr186P6GN8AH8rN78yHAEAAA==
      retrieved:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PQW+CMBiGvy1Z4sh+xq4kRSjCYQcznZZI2bQK7U1KndbWGQUD/q79wHHc8c3zPIfXAXDgZXVsjPm8/OwORg3gkVTwOpL+SEaxcmWoSjfAgXSjyI9d5OOo9NSwiivPAaePzupSH9T1GQa1auvmoq4OADwM4GmzNY2CX9UlSBR7VBWJkR0J+81WyGREn0fktOnKdxIS2/P5OFx08T8X19scG+4ne3H6akq7QQt/adR86Um7vnFGOs4+NNW8o1qidDZtU3ZsxWTspXqMaT4NBBN7kROPWo6zGblnE3FMrbCCfQd0SG3G0ju16yHXU8zvRvNDEu8K9NY/gD+IatwxHAEAAA==
      missed:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PvW6DMBhFv1aqRFEfoyuSCQHK0CH9S4yCaRICmM0mpmDsNEogCnmuPmDp1uEOV+fc4ZoAJjxs2l6pz+N31ShhwC3ewaPzxIKKcd9iPODWlAtuBYxxy54y4Qbc83npm2COo4M4do043YPRiUvXH8XJBIAbA+5SpnoBP2IIUZHXaJeHqhywN/Zkg1SM5cHH+3Tgr9jDeuSLmbccgn+u27HMVdQJ62K/6rlO0dJZK7FY26XenklGByqJJhPSUrl1o2uLaPIi47dQFwl1/hLJLxTplUOSVBZJreJ52hbzD1Vk2KUylfT67kQTbJNkdhl5S5owqHL0PD6AX2ZylXgcAQAA
    christmas:
      unavailable:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2OwW6CQBiE/zZpQkkfo1eSlWWhHnowVesSFwsqZbmxsgRwsUbBuPtUfcRy7GEOM99MMjaADS/b46DU1+WnapS04JGW8EpQVXiiwk5ZSex4AcKOQCV2girARAgigreJDfY4OstL38jrM1i9vPfDRV5tAHiw4Ckt1CDhV+oQ5VmNyixUB0390e+2SG1oew7oKdXig/q0G/lq5q/19F+X9MU3URyHdX6KB9GlaI0TJVfJ5NDtb/k8rLlZttFu4bF5qVjL79wsNDdJx7rlkY9iJm82n3TMYhK5TEem7CJDNXPTlrUx4i5FUTvzuNkTrsNplaH38T38AY7/bOUYAQAA
      available:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal:  H4sIAAAAAAAAAE2OwW6CQBiE/zZpQkkfo1eSlWWhHnowVesSFwsqZbmxsgRwsUbBuPtUfcRy7GEOM99MMjaADS/b46DU1+WnapS04JGW8EpQVXiiwk5ZSex4AcKOQCV2girARAgigreJDfY4OstL38jrM1i9vPfDRV5tAHiw4Ckt1CDhV+oQ5VmNyixUB0390e+2SG1oew7oKdXig/q0G/lq5q/19F+X9MU3URyHdX6KB9GlaI0TJVfJ5NDtb/k8rLlZttFu4bF5qVjL79wsNDdJx7rlkY9iJm82n3TMYhK5TEem7CJDNXPTlrUx4i5FUTvzuNkTrsNplaH38T38AY7/bOUYAQAA
      retrieved:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PQW+CMBiGvy1Z4sh+xq4kRSjCYQcznZZI2bQK7U1KndbWGQUD/q79wHHc8c3zPIfXAXDgZXVsjPm8/OwORg3gkVTwOpL+SEaxcmWoSjfAgXSjyI9d5OOo9NSwiivPAaePzupSH9T1GQa1auvmoq4OADwM4GmzNY2CX9UlSBR7VBWJkR0J+81WyGREn0fktOnKdxIS2/P5OFx08T8X19scG+4ne3H6akq7QQt/adR86Um7vnFGOs4+NNW8o1qidDZtU3ZsxWTspXqMaT4NBBN7kROPWo6zGblnE3FMrbCCfQd0SG3G0ju16yHXU8zvRvNDEu8K9NY/gD+IatwxHAEAAA==
      missed:
        ==: org.bukkit.inventory.ItemStack
        type: SKULL_ITEM
        damage: 3
        meta:
          ==: ItemMeta
          meta-type: SKULL
          internal: H4sIAAAAAAAAAE2PvW6DMBhFv1aqRFEfoyuSCQHK0CH9S4yCaRICmM0mpmDsNEogCnmuPmDp1uEOV+fc4ZoAJjxs2l6pz+N31ShhwC3ewaPzxIKKcd9iPODWlAtuBYxxy54y4Qbc83npm2COo4M4do043YPRiUvXH8XJBIAbA+5SpnoBP2IIUZHXaJeHqhywN/Zkg1SM5cHH+3Tgr9jDeuSLmbccgn+u27HMVdQJ62K/6rlO0dJZK7FY26XenklGByqJJhPSUrl1o2uLaPIi47dQFwl1/hLJLxTplUOSVBZJreJ52hbzD1Vk2KUylfT67kQTbJNkdhl5S5owqHL0PD6AX2ZylXgcAQAA
text:
  reward-received: "&aGeschenk des %day%. Dezembers erhalten!"
  unavailable: "&cDu musst noch warten!"
  available: "&aKlicke um dieses Geschenk zu öffnen!"
  retrieved: "&7Schon geöffnet."
  missed: "&7Diesen Tag hast du leider verpasst :("
  day: "&b%day%. Dezember%title%"
  advent: |-
    &b%day%. Dezember
    &6%advent%. Advent
  christmas: |-
    &b24. Dezember
    &6Heiligabend
  notification:
    today: "&aDu hast noch nicht das heutige Geschenk deines Adventskalenders geöffnet! ([&e/adventskalender](/adventskalender)&a)"
    before: "&aDu hast noch nicht das gestrige Geschenk deines Adventskalenders geöffnet! ([&e/adventskalender](/adventskalender)&a)"
    today-and-before: "&aDu kannst zwei Geschenke in deinem Adventskalender öffnen! ([&e/adventskalender](/adventskalender)&a)"
# Delay in seconds before sending notification messages after a player joins (-1 to disable notification)
notification-delay: 5
# How many days one can miss before a reward can no longer be claimed
missed-days: 1